version: '3.9'

services: 
  node_backend:
        container_name: elite-bn-be
        image: elite-bn-be:0.0.1
        build: 
            context: .
            args:
              - PORT:${PORT}
        volumes:
            - ./:/src/app
        ports: 
            - "3000:3000"
        environment: 
            - PORT=${PORT}
            - PGPORT=5432
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGHOST=db
        depends_on: 
            - db

  db:
    image: postgres:12
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  


